---

- name: Create ECR repository
  ecs_ecr:
    name: "{{ ecr_name }}"
    region: "{{ region }}"
  register: _ecr
  tags:
    - ecr

- debug:
    var: _ecr
  tags:
    - ecr

- set_fact:
    full_destination_image: "{{ _ecr.repository.repositoryUri }}:{{ destination_image_tag }}"
  tags:
    - ecr

- name: Tag image with repository and tag
  command: docker tag "{{source_image_name}}:{{ source_image_tag }}" "{{ full_destination_image }}"
  tags:
    - ecr

- name: Login to ECR
  shell: "$(aws ecr get-login --no-include-email --region {{ region }})"
  tags:
    - ecr

- name: "Push image to {{ full_destination_image }}"
  command: docker push "{{ full_destination_image }}"
  tags:
    - ecr
