---

- name: Create ECR repository
  ecs_ecr:
    name: "{{ ecr_name }}"
    region: "{{ region }}"
  register: _ecr
  tags:
    - ecr

- name: Debug ECR repository
  debug:
    var: _ecr
  when: debugging is defined
  tags:
    - ecr

- name: Set full_destination_image
  set_fact:
    full_destination_image: "{{ _ecr.repository.repositoryUri }}:{{ destination_image_tag }}"
  tags:
    - ecr

- name: Login to ECR  # TODO: Consider using https://github.com/awslabs/amazon-ecr-credential-helper
  shell: "$(aws ecr get-login --no-include-email --region {{ region }})"
  tags:
    - ecr

- name: Tag and push image
  docker_image:
    name: "{{source_image_name}}:{{ source_image_tag }}"
    repository: "{{ _ecr.repository.repositoryUri }}"
    tag: "{{ destination_image_tag }}"
    push: yes
  tags:
    - ecr
